server:
  ssl:
    key-store: springboot.p12
    key-store-password: password
    key-store-type: pkcs12
    key-password: password
    enabled: true
    key-alias: springboot
spring:
  cloud:
    gateway:
      routes:
        - id: monitoring
          uri: http://monitoring-service:8080
          predicates:
            - Path=/v1/track
      httpclient:
        ssl:
          use-insecure-trust-manager: true