server:
  ssl:
    key-store: keystore.p12
    key-store-password: changeit
    key-store-type: PKCS12
    key-password: changeit
    enabled: true
    key-alias: samokatim
    enabled-protocols: TLSv1.2
spring:
  cloud:
    gateway:
      routes:
        - id: monitoring
          uri: http://monitoring-service:8080
          predicates:
            - Path=/v1/track
      globalcors:
        cors-configurations:
          '[/**]':
              allowedOrigins: "*"
              allowCredentials: true
              allowedMethods:
                - GET
                - POST
                - PUT
                - OPTIONS
                - PATCH
                - DELETE