server:
  ssl:
    key-store: ./keystore.p12
    key-store-password: password
    key-store-type: pkcs12
    key-alias: springboot
    key-password: password
spring:
  cloud:
    gateway:
      routes:
        - id: monitoring
          uri: http://monitoring-service:8080
          predicates:
            - Path=/v1/track
